config/routes.rb
Rails.application.routes.draw do
  resources :chemicals
  resources :chemicals

  root 'chemicals#index'
  resources :chemicals

end

app/models/chemical.rb
class Chemical < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chemicals_controller.rb
class ChemicalsController < ApplicationController
  before_action :set_chemical, only: [:show, :edit, :update, :destroy]

  # GET /chemicals
  # GET /chemicals.json
  def index
    @chemicals = Chemical.all
  end

  # GET /chemicals/1
  # GET /chemicals/1.json
  def show
  end

  # GET /chemicals/new
  def new
    @chemical = Chemical.new
  end

  # GET /chemicals/1/edit
  def edit
  end

  # POST /chemicals
  # POST /chemicals.json
  def create
    @chemical = Chemical.new(chemical_params)

    respond_to do |format|
      if @chemical.save
        format.html { redirect_to @chemical, notice: 'Chemical was successfully created.' }
        format.json { render :show, status: :created, location: @chemical }
      else
        format.html { render :new }
        format.json { render json: @chemical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chemicals/1
  # PATCH/PUT /chemicals/1.json
  def update
    respond_to do |format|
      if @chemical.update(chemical_params)
        format.html { redirect_to @chemical, notice: 'Chemical was successfully updated.' }
        format.json { render :show, status: :ok, location: @chemical }
      else
        format.html { render :edit }
        format.json { render json: @chemical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chemicals/1
  # DELETE /chemicals/1.json
  def destroy
    @chemical.destroy
    respond_to do |format|
      format.html { redirect_to chemicals_url, notice: 'Chemical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chemical
      @chemical = Chemical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chemical_params
      params.require(:chemical).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemicals_helper.rb
module ChemicalsHelper
end

app/views/chemicals/_form.html.erb
<%= form_for(@chemical) do |f| %>
  <% if @chemical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chemical.errors.count, "error") %> prohibited this chemical from being saved:</h2>

      <ul>
      <% @chemical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chemicals/edit.html.erb
<h1>Editing Chemical</h1>

<%= render 'form' %>

<%= link_to 'Show', @chemical %> |
<%= link_to 'Back', chemicals_path %>

app/views/chemicals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chemicals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chemicals.each do |chemical| %>
      <tr>
        <td><%= chemical.name %></td>
        <td><%= link_to 'Show', chemical %></td>
        <td><%= link_to 'Edit', edit_chemical_path(chemical) %></td>
        <td><%= link_to 'Destroy', chemical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chemical', new_chemical_path %>

app/views/chemicals/new.html.erb
<h1>New Chemical</h1>

<%= render 'form' %>

<%= link_to 'Back', chemicals_path %>

app/views/chemicals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chemical.name %>
</p>

<%= link_to 'Edit', edit_chemical_path(@chemical) %> |
<%= link_to 'Back', chemicals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chemicals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>